<?php

namespace Totalcan\DocumancerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
    public function findByUserId($id)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT d FROM TotalcanDocumancerBundle:Client d WHERE d.userId = '.$id.' ORDER BY d.id DESC'
            );

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
