<?php

namespace Totalcan\DocumancerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
    public function listAll()
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT d FROM TotalcanDocumancerBundle:Document d ORDER BY d.id DESC'
            );

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
