<?php

namespace Totalcan\DocumancerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TemplateDesignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateDesignRepository extends EntityRepository
{
}
