<?php

namespace Totalcan\DocumancerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getUsersList()
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT d FROM TotalcanDocumancerBundle:User d ORDER BY d.id DESC'
            );

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
