security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false
        Totalcan\DocumancerBundle\Entity\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_COMPANY_OPERATOR:       ROLE_USER
        ROLE_COMPANY_ADMIN:       ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_MANAGER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_MANAGER]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    tarasss: { password: f90ec1c5bd43711a3f37549d730a11b3df1f28db, roles: [ 'ROLE_SUPER_ADMIN' ] }
        user_db:
            entity: { class: Totalcan\DocumancerBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false
        bravoreg:
            pattern:  ^/super/.*
            security: false
        cron:
            pattern:  ^/import/.*
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: security_check
                login_path: login
                post_only: false
                username_parameter: _username
                password_parameter: _password
                always_use_default_target_path: true
                default_target_path: homepage
            logout:
                path:   logout
                target: homepage

    access_control:
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,       role: ROLE_USER }


