security:
    access_control:
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,       role: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_COMPANY_OPERATOR:       ROLE_USER
        ROLE_COMPANY_ADMIN:       [ROLE_USER, ROLE_COMPANY_OPERATOR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    user: { password: ed9cc91baba23bba9a3ff37a259b9262c969e767, roles: [ 'ROLE_USER' ] }
        user_db:
            entity: { class: Totalcan\DocumancerBundle\Entity\User, property: username }

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false
        Totalcan\DocumancerBundle\Entity\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false


        login:
            pattern:  ^/login.*
            security: false

        secured_area:
            switch_user: { role: ROLE_SUPER_ADMIN, parameter: _change_user }
            pattern:    ^/
            form_login:
                check_path: security_check
                login_path: login
                post_only: false
                username_parameter: _username
                password_parameter: _password
                always_use_default_target_path: true
                default_target_path: homepage

            logout:
                path:   logout
                target: homepage


