totalcan_documancer_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: TotalcanDocumancerBundle:Document:index }
totalcan_documancer_image:
    pattern:  /image/{name}
    defaults: { _controller: TotalcanDocumancerBundle:Document:image }
totalcan_documancer_template:
    pattern:  /template/{name}
    defaults: { _controller: TotalcanDocumancerBundle:Document:template }
totalcan_documancer_url:
    pattern:  /url/{name}
    defaults: { _controller: TotalcanDocumancerBundle:Document:url }
totalcan_documancer_entity:
    pattern:  /entity
    defaults: { _controller: TotalcanDocumancerBundle:Document:entity }
totalcan_documancer_new_user:
    pattern:  /new/user
    defaults: { _controller: TotalcanDocumancerBundle:Document:new }
