admin:
    pattern:  /admin
    defaults: { _controller: TotalcanDocumancerBundle:Admin:index }
homepage:
    pattern:  /
    defaults: { _controller: TotalcanDocumancerBundle:Frontpage:index }

login:
    pattern:  /login
    defaults: { _controller: TotalcanDocumancerBundle:Admin:login }
login_check:
    pattern:  /login_check
    defaults: { _controller: TotalcanDocumancerBundle:Admin:securityCheck }
logout:
    pattern:  /logout
    defaults: { _controller: TotalcanDocumancerBundle:Admin:logout }

document_list:
    pattern:  /document/list
    defaults: { _controller: TotalcanDocumancerBundle:Document:list }
document_new:
    pattern:  /document/new
    defaults: { _controller: TotalcanDocumancerBundle:Document:new }
document_edit:
    pattern:  /document/edit/{id}
    requirements:
        id:  \d+
    defaults: { _controller: TotalcanDocumancerBundle:Document:edit }
document_delete:
    pattern:  /document/delete/{id}
    requirements:
        id:  \d+
    defaults: { _controller: TotalcanDocumancerBundle:Document:delete }
document_show:
    pattern:  /document/{id}
    requirements:
        id:  \d+
    defaults: { _controller: TotalcanDocumancerBundle:Document:show }
document_pdf:
    pattern:  /document/dl/{id}.pdf
    requirements:
        id:  \d+
    defaults: { _controller: TotalcanDocumancerBundle:Document:pdf }
document_jpg:
    pattern:  /document/dl/{id}.jpg
    requirements:
        id:  \d+
    defaults: { _controller: TotalcanDocumancerBundle:Document:image }

client_list:
    pattern:  /client/list
    defaults: { _controller: TotalcanDocumancerBundle:Client:list }
client_new:
    pattern:  /client/new
    defaults: { _controller: TotalcanDocumancerBundle:Client:new }
client_edit:
    pattern:  /client/edit/{id}
    defaults: { _controller: TotalcanDocumancerBundle:Client:edit }
client_delete:
    pattern:  /client/delete/{id}
    defaults: { _controller: TotalcanDocumancerBundle:Client:delete }

design_list:
    pattern:  /design/list
    defaults: { _controller: TotalcanDocumancerBundle:Design:list }
design_new:
    pattern:  /design/new
    defaults: { _controller: TotalcanDocumancerBundle:Design:new }
design_edit:
    pattern:  /design/edit/{id}
    defaults: { _controller: TotalcanDocumancerBundle:Design:edit }
design_delete:
    pattern:  /design/delete/{id}
    defaults: { _controller: TotalcanDocumancerBundle:Design:delete }
design_show:
    pattern:  /design/{id}
    defaults: { _controller: TotalcanDocumancerBundle:Design:show }

user_list:
    pattern:  /user/list
    defaults: { _controller: TotalcanDocumancerBundle:User:list }
user_new:
    pattern:  /user/new
    defaults: { _controller: TotalcanDocumancerBundle:User:new }
user_edit:
    pattern:  /user/edit/{id}
    defaults: { _controller: TotalcanDocumancerBundle:User:edit }
user_delete:
    pattern:  /user/delete/{id}
    defaults: { _controller: TotalcanDocumancerBundle:User:delete }
user_show:
    pattern:  /user/{id}
    defaults: { _controller: TotalcanDocumancerBundle:User:show }

template_list:
    pattern:  /template/list
    defaults: { _controller: TotalcanDocumancerBundle:Template:list }
template_new:
    pattern:  /template/new
    defaults: { _controller: TotalcanDocumancerBundle:Template:new }
template_edit:
    pattern:  /template/edit/{id}
    defaults: { _controller: TotalcanDocumancerBundle:Template:edit }
template_delete:
    pattern:  /template/delete/{id}
    defaults: { _controller: TotalcanDocumancerBundle:Template:delete }
template_show:
    pattern:  /template/{id}
    defaults: { _controller: TotalcanDocumancerBundle:Template:show }